package com.goldmedal.aillm.ai.decision

import com.goldmedal.aillm.ai.engine.OnDeviceEngine

/** The id of the `laya-multilingual` entry in the catalogue. */
const val LAYA_MODEL_ID = "laya-multilingual"

/**
 * Laya's three typed decision primitives.
 *
 * A question is not free text handed to a chat model: it declares *what kind*
 * of answer is wanted, and Laya scores one marker token per answer option.
 * `qtype` is the integer the ONNX graph takes, and it also indexes the
 * calibration table in the checkpoint's `rl_agent_config.json`.
 */
enum class LayaQuestionType(
    val qtype: Int,
    /** The name used in the prompt ("<type> question: <instructions>"). */
    val key: String,
    val displayName: String,
    /** How many options this primitive renders. 0 means "caller defined". */
    val optionCount: Int
) {
    CHOICE(0, "choice", "Choice", 0),
    SCORE(1, "score", "Score", 0),
    NOUL(2, "noul", "Noul / Yes-No", 2);

    /** noul is always a two-option false/true question in this app. */
    val isYesNo: Boolean get() = this == NOUL

    companion object {
        fun fromQtype(value: Int): LayaQuestionType? =
            values().firstOrNull { it.qtype == value }
    }
}

/**
 * The three-way verdict scale the screen shows.
 *
 * The verdict is derived only from the model's calibrated probability that the
 * question holds; it is never generated by the model. The C (Not Clear) band is
 * the app's own statement that the probability sits at a coin flip.
 *
 * ```
 * probability >= 51%          -> Y
 * probability <= 49%          -> N
 * 49% < probability < 51%     -> C (Not Clear)
 * ```
 */
enum class DecisionVerdict {
    Y,
    N,
    C;

    companion object {
        /** The band's edges, as probabilities. */
        const val YES_THRESHOLD = 0.51f
        const val NO_THRESHOLD = 0.49f

        fun fromProbability(probability: Float): DecisionVerdict = when {
            probability >= YES_THRESHOLD -> Y
            probability <= NO_THRESHOLD -> N
            else -> C
        }
    }
}

/**
 * Everything the debug view needs to prove that one judgment followed Laya's
 * real pipeline: the exact qtype, the marker positions inside the token
 * sequence, the raw logits the graph returned, the calibration temperature that
 * was applied, and the resulting false/true probabilities.
 */
data class DecisionDebug(
    val questionType: LayaQuestionType,
    val subject: String,
    val question: String,
    /** Token indices of the option `[MASK]` markers, in label order. */
    val markerPos: List<Int>,
    /** Raw `logits[batch, markers]` for this row, before calibration. */
    val rawLogits: List<Float>,
    /** Softmax over the option logits, in label order. */
    val probabilities: List<Float>,
    /** The temperature actually divided into the logits. */
    val temperature: Float,
    /** The raw temperature settings the checkpoint shipped. */
    val temperatureConfig: List<Float>
) {
    val qtype: Int get() = questionType.qtype
    val pFalse: Float get() = probabilities.getOrElse(0) { Float.NaN }
    val pTrue: Float get() = probabilities.getOrElse(1) { Float.NaN }
}

/** One answered judgment. */
data class DecisionResult(
    /** The state the question was asked about (one line of the State field). */
    val subject: String,
    /** The question's instructions. */
    val question: String,
    val questionType: LayaQuestionType,
    val verdict: DecisionVerdict,
    /** Calibrated probability that the question holds (noul's P(true)). */
    val probability: Float,
    val debug: DecisionDebug
)

/**
 * Why a single row could not be judged. Every entry is an explicit state, never
 * a silently substituted guess: there is no heuristic fallback and no "??"
 * pseudo-answer anywhere in this feature.
 */
enum class DecisionFailureKind(val label: String) {
    MODEL_NOT_LOADED("モデルが読み込まれていません"),
    MODEL_MISSING("ONNXモデルが見つかりません"),
    TOKENIZER_MISSING("tokenizer.json が見つかりません"),
    TOKENIZER_ERROR("tokenizer エラー"),
    ONNX_ERROR("ONNX Runtime エラー"),
    MISSING_MARKER("marker が不足しています"),
    LOGITS_MISSING("logits が不足しています"),
    INVALID_PROBABILITY("確率が不正です (NaN / 範囲外)");

    /** The one line the results list shows for a failed row. */
    val displayMessage: String get() = "判定できませんでした · $label"
}

/** A row-level failure, with an optional technical detail for the debug view. */
data class DecisionFailure(
    val kind: DecisionFailureKind,
    val detail: String? = null
)

/**
 * The outcome of one state in a Laya batch. A batch can mix answers and
 * failures: one row with an unusable probability does not discard the others.
 */
sealed interface DecisionOutcome {
    val subject: String

    data class Answered(
        override val subject: String,
        val result: DecisionResult
    ) : DecisionOutcome

    data class Failed(
        override val subject: String,
        val failure: DecisionFailure
    ) : DecisionOutcome
}

/**
 * The Decision AI: convaiinnovations/laya-multilingual, a non-autoregressive
 * "System One" decision model covering 100+ languages.
 *
 * Laya is *not* a chat model. It never generates text: it tokenizes a structured
 * prompt, reads the logits at one `[MASK]` marker per answer option, applies the
 * checkpoint's fitted temperature, and returns a probability distribution over
 * those options. It runs on its own ONNX Runtime (`:onnx`), independently of the
 * llama.cpp chat model.
 *
 * A batch of states asked the same question shares one forward pass.
 */
interface DecisionModel : OnDeviceEngine {
    /**
     * Judges [question] for every line in [states] and answers each with Y, N or
     * C — or a [DecisionOutcome.Failed] when Laya's output cannot be trusted.
     *
     * A failure of the engine itself (not loaded, no tokenizer, no graph) is a
     * failed [Result]; a failure of one row's output is reported per row.
     */
    suspend fun decide(
        states: List<String>,
        question: String,
        questionType: LayaQuestionType = LayaQuestionType.NOUL
    ): Result<List<DecisionOutcome>>
}
